
services:
  # =====================
  # KONG API GATEWAY (DB-less)
  # =====================
  kong:
    image: kong
    container_name: kong
    restart: unless-stopped
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/kong/kong.yml"
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_LOG_LEVEL: debug
      KONG_PLUGINS: bundled,correlation-id

    volumes:
      - ./kong/kong.yml:/kong/kong.yml:ro

    ports:
      - "9000:8000"
      - "8001:8001"

    depends_on:
      - auth_service

    networks:
      - project_network

  # =====================
  # REDIS
  # =====================
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - project_network

  # =====================
  # AUTH SERVICE & DB
  # =====================
  auth_db:
    image: postgres:15-alpine
    container_name: auth_db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    networks:
      - project_network

  auth_service:
    build: ./auth_service
    container_name: auth_service
    env_file:
      - ./auth_service/.env
    ports:
      - "8000:8000"
    depends_on:
      - auth_db
    volumes:
      - ./auth_service:/app
    command: ["/app/entrypoint.sh"]
    restart: unless-stopped
    networks:
      - project_network

  # =====================
  # RH SERVICE & DB
  # =====================
  rh_db:
    image: postgres:15-alpine
    container_name: rh_db
    environment:
      POSTGRES_DB: rh_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - rh_postgres_data:/var/lib/postgresql/data
    networks:
      - project_network

  rh_service:
    build: ./rh_service
    container_name: rh_service
    env_file:
      - ./rh_service/.env
    environment:
      DJANGO_ALLOWED_HOSTS: "*,localhost,127.0.0.1,rh_service,auth_service,kong"
      DJANGO_DEBUG: "True"
      DATABASE_URL: "postgres://postgres:postgres@rh_db:5432/rh_db"
    depends_on:
      - rh_db
      - auth_service
    ports:
      - "8002:8000"
    networks:
      - project_network






  # =====================
  # FRONTEND
  # =====================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:80"
    environment:
      - API_URL=http://localhost:9000/api
    depends_on:
      - kong
    restart: unless-stopped
    networks:
      - project_network

# =====================
# RÃ©seaux & Volumes
# =====================
networks:
  project_network:
    driver: bridge

volumes:
  auth_postgres_data:
  redis_data:
  rh_postgres_data:

