
services:
  kong:
    image: kong:3.4
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PROXY_LISTEN: 0.0.0.0:8443 ssl
      KONG_SSL_CERT: /kong/ssl/cert.pem
      KONG_SSL_CERT_KEY: /kong/ssl/key.pem
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_LOG_LEVEL: debug
      KONG_PLUGINS: bundled,correlation-id
    volumes:
      - ./kong/kong.yml:/kong/kong.yml:ro
      - ./kong/ssl:/kong/ssl:ro    # <--- ajouter ce volume
    ports:
      - "443:8443"   # HTTPS public
      - "80:8000"    # HTTP public (optionnel)
      - "8001:8001"  # Admin (attention prod)
    depends_on:
      - auth_service
      - rh_service
      - stock_service
      - finance_service
      - cordo_service
    networks:
      - project_network

  auth_service:
    build: ./auth_service
    container_name: auth_service
    env_file:
      - ./auth_service/.env
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - project_network

  rh_service:
    build: ./rh_service
    container_name: rh_service
    env_file:
      - ./rh_service/.env
    ports:
      - "8002:8000"
    restart: unless-stopped
    networks:
      - project_network

  stock_service:
    build: ./stock_service
    container_name: stock_service
    env_file:
      - ./stock_service/.env
    ports:
      - "8003:8000"
    restart: unless-stopped
    networks:
      - project_network

  finance_service:
    build: ./finance_service
    container_name: finance_service
    env_file:
      - ./finance_service/.env
    ports:
      - "8004:8000"
    restart: unless-stopped
    networks:
      - project_network

  cordo_service:
    build: ./cordo_service
    container_name: cordo_service
    env_file:
      - ./cordo_service/.env
    ports:
      - "8005:8000"
    restart: unless-stopped
    networks:
      - project_network

networks:
  project_network:
    driver: bridge
